language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
before_install:
- sudo apt-get install -y build-essential
- npm install -g node-gyp
install: npm install
