defaults:
  hostname:           https://docs.taskcluster.net
  port:               !env:number PORT
  forceSSL:           false
  trustProxy:         false
  events:
    statsComponent:   events
  env:                !env ENV

  pulse:
    username:         !env PULSE_USERNAME
    password:         !env PULSE_PASSWORD

  taskcluster:
    credentials:
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN
      clientId:       !env TASKCLUSTER_CLIENT_ID
