defaults:
  pulse:
    username:           ckousik
    password:           '*3!!ip5is*'

  taskcluster:
    # if clientId is persona/chinmaykousik1@gmail.com/tc-diagnostics, then
    # baseclientId will be persona/chinmaykousik1@gmail.com/
    baseClientId:       project/taskcluster/tc-diagnostics/development/
    credentials:
      accessToken:      3vOr-ahzTlO1JEWGglNfywVEf6Y0XGT9mWmHhjgmwprQ
      clientId:         project/taskcluster/tc-diagnostics/development
  aws:
    AccessKeyId:        AKIAJWCY7QVW5EZB74HQ
    SecretAccessToken:  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
